---
root: true
extends:
  - eslint:recommended
  - plugin:react/recommended
settings:
  react:
    createClass: createReactClass
    pragma: React
    version: detect
    flowVersion: 0.53
  propWrapperFunctions:
    - forbidExtraProps
    - {property:freeze, object:Object}
    - {property:myFavoriteWrapper}
...
