root: true
extends:
  - airbnb
  - prettier
env:
  browser: true
  node: true
  es6: true
  jest: true
  jasmine: true
parser: typescript-eslint-parser
plugins:
  - react
  - babel
  - typescript
  - react-hooks
rules:
  # import setting
  import/prefer-default-export: 0
  import/extensions: 0
  import/no-unresolved: 0
  # react setting
  react/prefer-stateless-function: 0
  react/jsx-indent: 0
  react/jsx-filename-extension: 0
  react/jsx-indent-props: 0
  react/prop-types: 0
  # jsx-a11y
  jsx-a11y/no-static-element-interactions: 0
  jsx-a11y/click-events-have-key-events: 0
  # react-hooks
  "react-hooks/rules-of-hooks": 2
  "react-hooks/exhaustive-deps": 2
  # default setting
  no-use-before-define: 0
  # 缩进
  indent:
    - 2
    - 4
    - SwitchCase: 1
  # 不要给我写分号
  semi:
    - 2
    - never
    - beforeStatementContinuationChars: always
  # 单引号
  quotes:
    - 2
    - single
  for-direction: 2
  # 可以用++符号
  no-plusplus: 0
  # 函数内部的参数可以被覆盖
  no-param-reassign: 0
  # 可以用打印函数
  no-console: 0
  # 可以用匿名函数
  func-names: 0
  # 可以使用位运算符
  no-bitwise: 0
  # 注释的空格问题就别给我提示了
  spaced-comment: 0
  # 没有用的参数给提醒就可以了
  no-unused-vars: 0
  no-dupe-class-members: 0
  lines-between-class-members: 0
