root: true
extends:
  - airbnb
  - prettier
env:
  browser: true
  node: true
  es6: true
  jest: true
  jasmine: true
parser: babel-eslint
plugins:
  - react
  - babel
rules:
  # import setting
  import/prefer-default-export: 0
  # react setting
  react/prefer-stateless-function: 0
  react/jsx-indent: 0
  react/jsx-filename-extension: 0
  react/jsx-indent-props: 0
  # jsx-a11y
  jsx-a11y/no-static-element-interactions: 0
  jsx-a11y/click-events-have-key-events: 0
  # default setting
  no-use-before-define: 0
  indent:
    - 2
    - 4
  semi:
    - 2
    - never
    - beforeStatementContinuationChars: always
  quotes:
    - 2
    - single
  for-direction: 2
  no-plusplus: 0
  no-param-reassign: 0
  no-console: 0
