language: node_js
node_js: stable
branches:
- only: master
install:
- yarn
before_script:
- git config --global user.name "travis-ci"
- git config --global user.email "752140235@qq.com"

script:
- yarn run build
- hexo generate
after_script:
# - hexo deploy
  - cd ./build
  - git init
  - git add .
  - git commit -m "Travis-CI update docs"
  - git push --force https://${REPO_TOKEN}@${GH_REF} master:gh-pages
env:
  global:
  - secure: TWm5m8sMQdNX+oHm0feRrRIcLIbph5IvCxT9+i66sPw2W2Qe4TYZKVpwVYIvxW6r/4LffCUiFR3IrOnPoxGi13n1W6kYAhpsK6YgaTBh38UxRhRM/768pPxA5O6Dt1USWpocSegbjF55828ODRb/nr2uIFDOhWVMZo22x/HdYQYWZM8TNXWccU1ZC08BrLivT/AanEn3NACBkLRT/5uhh2NA9/nv9MVxP+/X65mGBbGu6zolTky7cNxuRplglsx1trdfOUvWEDSPCBO8B2Rx4NB3XwOaDzVn3okY2jBjSz1jb9xiyESDyDmnjlMv9p+5LZkUx8kMWDtH7UY7F/y/az0i/M74gwE7BcZ6vdk+eCBjABkTqb8X/hG33Ttkr21AbM02E0BmDhyl2pim2xsnAGdSIQ4vY8YwgBDKbwe2ZoKZCjEoKvUc1HLboTi4Z52etQXIrKSVxlQR2gL14NwYrPiSdhA4jOKnDTxkuCTb4PFw4NgAfkqxPx9GezEfntaJX06//ZQo4B0v1AQ2RuYfY9k3XHNlwYIfk073MV2R7a2+r83ndYVIVhLP810vFn/ZuPuCR8gICbIZWW+ZsKnms9WTOVIrWxvkL0Ts1dwBov62T0HG7Ndck2AVtnym4wgDxPLXeTTwPg16L+za8lirLNQBs5Vz/h3SdcL9Kefig/w=
  - GH_REF: github.com/limengke123/tiny-waffle.git
